### ISSUE TITLE
Bug in literals minifier

### ISSUE THREAD

**Issue by kaifaty** [explodingcamera/esm#1]
I've receive an error 
` splitHTMLByPlaceholder() must return same number of strings as template parts`
when i try to minify component with styles like so:
```CSS
:host {
      ${LitLink.cssKey('color')}: ${this.cssVar('color')};
      display: inline-block;
      box-sizing: border-box;
      position: relative;
 }
```

The problem is in CleanCSS, it return warnings with wrong styles. 
I've solved it. On warnings now just removing spaces and \r\n: 

```Javascript
async minifyCSS(css, options = {}) {
    const adjustedOptions = adjustMinifyCSSOptions(options)
    const output = await new CleanCSS({
      ...adjustedOptions,
      returnPromise: true,
    }).minify(css)

    if (output.errors?.length) throw new Error(output.errors.join('\n\n'))
    if (output.warnings.length) {
      return fixCleanCssTidySelectors(css, css.replace(/(\n)|(\r)|(  )/g, ''))
    }
    return fixCleanCssTidySelectors(css, output.styles)
  }
```
